export interface Metadata {
  name: string
  labels?: {
    [key: string]: string
  } | null
  annotations?: {
    [key: string]: string
  } | null
  version?: number | null
  creationTimestamp?: string | null
  deletionTimestamp?: string | null
}

export interface CoverGenerateRecordSpec {
  status: 'PROCESSING' | 'SUCCESS' | 'FAILED'
  llmPrompt: string
  t2iPrompt: string
  llmProvider: string
  t2iProvider: string
  llmModelId: string
  t2iModelId: string
}

/**
 * Corresponds to the custom model CoverGenerateRecord
 */
export interface CoverGenerateRecord {
  spec: CoverGenerateRecordSpec
  apiVersion: 'io.github.curtion/v1alpha1'
  kind: 'CoverGenerateRecord'
  metadata: Metadata
}

/**
 * The type corresponding to the list API generated by the CoverGenerateRecord custom model
 */
export interface CoverGenerateRecordList {
  page: number
  size: number
  total: number
  items: Array<CoverGenerateRecord>
  first: boolean
  last: boolean
  hasNext: boolean
  hasPrevious: boolean
  totalPages: number
}
